---
oh2:
  image: 'cyberkov/openhab2'
  ports:
    - "8080:8080"
    - "8443:8443"
    - "5555:5555"
    - "9001:9001"
    - "9123:9123"
  net: "host"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - "/opt/openhab/userdata:/openhab/userdata"
    - "/opt/openhab/config:/openhab/conf"
  command: dockerize -stdout /userdata/logs/openhab.log /openhab/start.sh debug
  devices:
    - '/dev/ttyUSB0'

